[package]
name = "exgrid_example"
version = "0.2.0"
authors = ["PingPongun <pp.pp4@vp.pl>"]
edition = "2021"

[dependencies]
eframe = { version = "0.28" }
egui = { version = "0.28" }
exgrid = { path = ".." }

[[bin]]
name = "exgrid_example"
path = "./demo.rs"
